english_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('words/', include('words.urls')),
    path('games/', include('games.urls')),
]

games/urls.py
from django.urls import path
from . import views


app_name = 'games'
urlpatterns = [
    path('memorization/', views.memorization, name='memorization'),
    path('get_random_word', views.get_random_word, name='get_random_word'),
    path('check_word', views.check_word, name='check_word'),
]

home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),    
]

words/urls.py
from django.urls import path
from . import views

app_name = 'words'

urlpatterns = [
    path('', views.WordListView.as_view(), name='word_list'),
    path('add_word/', views.add_word, name='add_word'),
    path('video/', views.words_from_video, name='words_from_video'),
    path('video/add_word', views.words_from_video_handler, name='video_add_word'),
    path('delete_word/<int:pk>', views.delete_word, name='delete_word'),
]

games/models.py
from django.db import models

# Create your models here.

words/models.py
from django.db import models

class Word(models.Model):
    word = models.CharField(max_length=255)
    translation_to_ru = models.CharField(max_length=255, default="None")
    # Count of success translate
    guessed = models.PositiveIntegerField(default=0)
    # Count of fail with translate
    wrong = models.PositiveIntegerField(default=0)
    # Sentence where this word is present
    context = models.CharField(max_length=255, null=True, blank=True)
    # True, if word was learned
    archive = models.BooleanField(default=False)
    added_at = models.DateTimeField(auto_now_add=True, db_index=True)
    
    def __str__(self):
        return self.word

games/views.py
from django.shortcuts import render
from django.db.models import Count
from random import randint
from words.models import Word
from django.http import JsonResponse
from . import utils


def get_random_word(request):
    words_count = Word.objects.filter(archive=False).count()
    random_index = randint(0, words_count-1)
    word = Word.objects.filter(archive=False)[random_index]
    return JsonResponse({'word':word.word, 'context':word.context})

def memorization(request):
    return render(request, 'games/memorization.html')

def check_word(request):
    word = request.GET.get('word')
    translate = request.GET.get('translate')
    response = utils.check_translate_ai(word, translate)
    if response['result']:
        word_obj = Word.objects.get(word=word)
        word_obj.guessed += 1
        word_obj.translation_to_ru = response['translate'].capitalize()
        if word_obj.guessed == 3:
            word_obj.archive = True
        word_obj.save()
    else:
        word_obj = Word.objects.get(word=word)
        word_obj.wrong += 1
        word_obj.save()
    return JsonResponse(response)

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class Home(TemplateView):
    template_name = 'home/index.html'

words/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.http import JsonResponse
from .models import Word
from youtube_transcript_api import YouTubeTranscriptApi


class WordListView(ListView):
    template_name = 'words/index.html'
    def get_queryset(self):
        return Word.objects.filter(archive=False)

def add_word(request):
    word = request.POST.get('word').capitalize()
    Word.objects.create(word=word)
    return redirect('words:word_list')

def delete_word(request, pk):
    Word.objects.get(pk=pk).delete()
    return redirect('words:word_list')

def words_from_video(request):
    video_id = request.GET.get('video_id')
    transcript = YouTubeTranscriptApi.get_transcript(video_id)
    word_count = {}
    word_context = {}
    

    for t in transcript:
        full_text = t['text']
        text = full_text.replace('\n', ' ')
        text = text.split(' ')
        
        for word in text:
            if word in word_count:
                word_count[word] += 1
            else:
                if word.isalpha():
                    word = word.lower()
                    word_count[word] = 1
                    word_context[word] = full_text

    sorted_word_count = dict(sorted(word_count.items(), key=lambda item: item[1]))

    return render(request, 'words/words_from_yt.html', context={
        'words': sorted_word_count,
        'word_context': word_context,
    })
    
def words_from_video_handler(request):
    if request.method == 'POST':
        word = request.POST.get('word').capitalize()
        if Word.objects.filter(word=word).exists():
            return JsonResponse({'message': 'У вас уже есть это слово!', 'added': False})
        context = request.POST.get('context')
        word_obj = Word(word=word, context=context)
        word_obj.save()
        return JsonResponse({'message': 'Слово было добавлено', 'added': True})
    return JsonResponse({'message': 'This method doesn`t support'})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-200">
    {% include "includes/header.html" %}
    {% block main %}
    {% endblock main %}
</body>
</html>

templates/games/memorization.html
{% extends "base.html" %}
{% block title %}Запоминания{% endblock title %}
{% block main %}
<main class="grid grid-cols-2">
    <div class="h-fit">

        <div id="main-form" class="bg-white m-5 p-8 rounded-xl">
            <div id="play-form" class="hidden">
                <div id="loading" class="hidden flex items-center space-x-1 mb-1">
                    <div class="w-5 h-5">
                        <p class="text-gray-500 animate-spin text-xs">o</p>
                    </div>
                    <p class="text-gray-500 text-sm">Проверка</p>
                </div>
                
                <p id="play-form-header" class="font-semibold text-xl"></p>
                <div class="text-center mt-1">
                    <p id="context" class="italic font-light text-start mb-4"></p>
                    <div class="space-x-2">
                        <input id="play-form-input" type="text" class="bg-gray-100 rounded p-2" placeholder="">
                        <button id="play-form-button" type="submit"
                            class="rounded p-2 bg-sky-700 hover:bg-sky-800 text-white">Перевод</button>
                    </div>
                </div>
            </div>
            <div id="begin-form" class="flex items-center justify-center">
                <button id="begin-button" class="bg-sky-700 hover:bg-sky-800 rounded p-3 text-white">
                    Начать
                </button>
            </div>
        </div>

        <div id="success-form" class="hidden bg-green-200 m-5 p-3 rounded-lg text-green-800 text-center space-y-2">
            <div class="flex items-center space-x-5">
                <!-- <p class="bg-green-300 rounded-full w-9 h-9 flex items-center justify-center text-2xl">!</p> -->
                <p class="text-lg">✅</p>
                <p class="text-sm">Вы сделали правильный перевод!</p>
            </div>
            <button class="continue p-1 bg-green-300 rounded hover:bg-green-400">Продолжить</button>
        </div>

        <div id="error-form" class="hidden bg-red-200 m-5 p-3 rounded-lg text-red-800 text-center space-y-2">
            <div class="flex items-center space-x-5">
                <!-- <p class="bg-red-300 rounded-full w-9 h-9 flex items-center justify-center text-md">x</p> -->
                <p class="text-lg">❌</p>
                <p id="result-input" class="text-sm text-start"></p>
            </div>
            <button class="continue p-1 bg-red-300 rounded hover:bg-red-400">Продолжить</button>
        </div>
    </div>

    <div class="bg-white m-5 p-8 rounded-xl text-center h-fit">
        <p class="text-xl">Статистика</p>
    </div>
</main>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    word = null;
    <!-- Start -->
    function get_word() {
        $.ajax({
            url: "{% url 'games:get_random_word' %}",
            type: "GET",
            success: function (response) {
                word = response.word                
                $('#begin-form').hide()
                $('#play-form').removeClass('hidden')
                text = `Введите перевод слова ${response.word}`
                context = `'${response.context}'`
                $('#context').text(context)
                $('#play-form-header').text(text)
                $('#play-form-input').attr('placeholder', response.word)
            }
        });
    }

    $('#begin-button').click(get_word);
    $('.continue').click(function(){
        $('#success-form').addClass('hidden')
        $('#error-form').addClass('hidden')
        $('#play-form-input').val("")
        get_word()
    });

    $('#play-form-button').click(function () {
        class_for_wait = "bg-gray-300 opacity-70"
        $('#loading').removeClass('hidden')
        $('#main-form').addClass(class_for_wait)

        $.ajax({
            url: "{% url 'games:check_word' %}",
            data: {
                word: word,
                translate: $('#play-form-input').val()
            },
            type: "GET",
            success: function (response) {
                if (response.result) {
                    $('#success-form').removeClass('hidden')
                } else {
                    $('#error-form').removeClass('hidden')
                    $('#result-input').text(response.explanation)
                }
            },
            complete: function(){
                $('#loading').addClass('hidden')
                $('#main-form').removeClass(class_for_wait)
            }
        })
    })




</script>
{% endblock main %}

templates/home/index.html
{% extends "base.html" %}
{% block title %} Главная страница {% endblock title %}
{% block main %}

<main>
    <div class="bg-white rounded-lg m-3 p-3">
        <p class="text-lg font-semibold">Как пользоваться приложением</p>
        <p class="font-light">
            1) Посмотрите или почитайте контент на английском языке.
            <br>
            2) Загрузите на сайт видео и добавьте незнакомые вам слова.
            <br>
            3) Попробуйте давать перевод этим словам в разделе "Запоминания" и получайте рекомендации от 
            <span class="text-purple-700 animate-pulse">искусственного интеллекта</span>
        </p>
    </div>

    <div class="bg-white rounded-lg m-3 p-3">
        <p class="text-lg font-semibold">Рекомендации по изучении английского языка</p>
        <p class="font-light">
            1) Погружение в среду: Смотрите фильмы, слушайте подкасты, читайте книги и статьи на английском языке.
            Это
            поможет вам привыкнуть к звучанию и структуре языка.
            <br>
            2) Регулярная практика: Ежедневные короткие сессии (15-30 минут) будут эффективнее, чем редкие, но
            долгие
            занятия.
            <br>
            3) Активное использование: Общайтесь на английском с носителями языка или партнёрами по языковому
            обмену.
            Практика важна для уверенного использования.
            <br>
            4) Расширение словарного запаса: Изучайте новые слова в контексте, а не изолированно. Например,
            записывайте и
            повторяйте выражения целиком.
            <br>
            5) Работа над грамматикой: Изучайте базовые правила грамматики и старайтесь применять их на практике.
            Используйте приложения и онлайн-курсы для структурированного изучения.
            <br>
            6) Письменные упражнения: Ведение дневника на английском или переписка с носителями языка поможет
            улучшить
            навыки письма.
            <br>
            7) Настройка на успех: Не бойтесь ошибок. Они – часть процесса обучения.
        </p>
    </div>
</main>
{% endblock main %}

templates/includes/header.html
<header class="bg-white p-3 flex items-center justify-between">
    <div class="space-x-2">
        <a href="{% url "home:home" %}" class="font-bold font-serif hover:text-gray-500">Главная</a>
        <a href="{% url "words:word_list" %}" class="font-bold font-serif hover:text-gray-500 ">Мои слова</a>
        <a href="{% url "games:memorization" %}" class="font-bold font-serif hover:text-gray-500">Запоминания</a>
    </div>
    <a href="" class="flex items-center space-x-3 hover:bg-gray-100 hover:cursor-pointer p-2 rounded">
        <p class=" font-light">Никнейм</p>

        <div class="w-8 h-8 rounded-full bg-stone-200">
            <img src="" alt="">
        </div>
    </a>
</header>

templates/words/index.html
{% extends "base.html" %}
{% load static %}

{% block title %} Слова {% endblock title %}  
{% block main %}

<main class="grid grid-cols-2 gap-3 m-5">
    <div class="bg-white rounded p-3 h-fit">
        <p class="text-2xl font-serif text-center">Мои слова</p>
        <div class="max-h-96 overflow-scroll space-y-3 mt-5">

            <div class="font-serif text-xl grid grid-cols-4 gap-4">
                <p>Слово</p>
                <p>Перевод</p>
                <p>Отгадано раз</p>
            </div>

            {% for obj in object_list %}
            <div class="grid grid-cols-4 gap-4 flex items-center">
                <p>{{ obj.word }}</p>
                {% if obj.translation_to_ru == 'None' %}
                <a class="group" href="{% url "games:memorization" %}">
                    <p class="bg-gray-200 text-gray-500 hover:bg-gray-100 hover:cursor-pointer text-center rounded w-8/12">?</p>
                    <p class="hidden group-hover:block absolute bg-gray-50 p-2 rounded italic text-sm font-light">Попробуйте отгадать слово в игре</p>
                </a>
                {% else %}
                <p>{{ obj.translation_to_ru }}</p>
                {% endif %}
                <p>{{ obj.guessed }}</p>
                <a href="{% url 'words:delete_word' obj.pk %}" class="bg-red-700 p-1 rounded w-fit hover:bg-red-800 hover:scale-110"><img src="{% static 'svg/trash.svg' %}" class="w-6"></a>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="bg-white rounded p-3 h-fit">
        <p class="text-2xl font-serif text-center">Добавить слова</p>
        <div class="flex flex-col text-center mt-5 space-y-3">
            <div class="group flex flex-col">
                <button class="bg-stone-400 hover:bg-stone-500 rounded text-white p-2 font-bold">
                    Добавить свое слово
                </button>
                <div class="relative hidden group-focus-within:block top-1 bg-stone-400 rounded p-3 text-white text-sm">
                    <form action="{% url "words:add_word" %}" method='post' class="text-base font-light space-x-5">
                        {% csrf_token %}
                        <label for="" class="font-semibold">
                            Напишите английское слово
                        </label>
                        <input name='word' type="text" class="p-1 rounded text-black">
                        <button type="submit" class="p-2 rounded bg-white hover:bg-gray-100 text-black font-semibold">Отправить</button>
                    </form>
                </div>
            </div>

            <div class="group flex flex-col">
                <button class="bg-stone-400 hover:bg-stone-500 rounded text-white p-2 font-bold">
                    Добавить с текста
                </button>
                <div class="relative hidden group-focus-within:block top-1 bg-stone-400 rounded p-3 text-white text-sm">
                    <form action="" class="text-base font-light space-x-5">
                        <label for="" class="font-semibold">
                            Вставьте текст
                        </label>
                        <input type="text" class="p-1 rounded text-black">
                        <button type="submit" class="p-2 rounded bg-white hover:bg-gray-100 text-black font-semibold">Отправить</button>
                    </form>
                </div>
            </div>

            <div class="group flex flex-col">
                <button class="bg-red-500 hover:bg-red-600 rounded text-white p-2 font-bold">
                    Добавить с YouTube видео
                </button>
                <div class="relative hidden group-focus-within:block top-1 bg-red-500 rounded p-3 text-white text-sm">
                    <form action="{% url "words:words_from_video" %}" class="text-base font-light space-x-5">
                        <label for="" class="font-semibold">
                            Вставьте id видео
                        </label>
                        <div class="group/hint inline">
                            <p class="inline w-fit bg-slate-400 hover:bg-slate-300 opacity-40 hover:cursor-pointer p-1 rounded">?</p>
                            <p class="absolute hidden group-hover/hint:block left-72 bottom-12 opacity-80 bg-gray-200 text-black font-light text-xs p-2 rounded">
                                Скопируйте строку после 'watch?v=' и до &(если имеется)
                            </p>
                        </div>
                        <input type="text" class="p-1 rounded text-black" name='video_id'>
                        <button type="submit" class="p-2 rounded bg-white hover:bg-gray-100 text-black font-semibold">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock main %}

templates/words/words_from_yt.html
{% extends "base.html" %}

{% load custom_filters %}
{% block title %}Слова с ролика{% endblock title %}
{% block main %}

<main>
    <div id="response-message" class=" opacity-65 text-white font-light p-5 m-3 text-center rounded"></div>
    <div class="bg-white rounded p-3 m-3">
        <p class="text-2xl font-serif text-center">Все слова с ролика</p>
        <hr>
        <div class="grid grid-cols-3 gap-2 text-center mt-4 font-serif text-lg">
            <p>Слово</p>
            <p>Контекст</p>
            <p>Добавить</p>
        </div>

        <div class="h-[70vh] overflow-scroll">
                {% for k, v in words.items %}
                <div class="grid grid-cols-3 gap-2 text-center mt-4 font-serif text-lg {% if forloop.counter|divisibleby:2 == 0 %}bg-gray-100{% endif %} p-2 rounded">
                    <p>{{k}}</p>
                    <p>{{ word_context|get_item:k }}</p>
                    <button data-word="{{ k }}" data-context="{{ word_context|get_item:k }}"
                        class="add-word bg-green-500 hover:bg-green-600 text-white rounded font-sans font-medium text-sm place-content-center w-1/2 mx-auto">Добавить</button>
                </div>
                {% endfor %}
        </div>

    </div>
</main>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $('.add-word').click(function () {
        var word = $(this).data('word');
        var context = $(this).data('context');

        $.ajax({
            url: '{% url "words:video_add_word" %}',
            type: 'POST',
            data: {
                word: word,
                context: context,
                csrfmiddlewaretoken: '{{csrf_token}}'
            },
            success: function (response) {
                var messageElement = $('#response-message');
                messageElement.text(response.message)
                messageElement.removeClass('bg-green-700 bg-red-700')
                if (response.added) {
                    messageElement.addClass('bg-green-700')
                } else {
                    messageElement.addClass('bg-red-700')
                }

                anim_class = 'opacity-35 transition-opacity duration-500'
                messageElement.addClass(anim_class);
                setTimeout(function(){
                    messageElement.removeClass(anim_class)
                }, 500)
            }
        })
    })
</script>

{% endblock main %}